### ISSUE TITLE
Installed Successfully but getting this error after restarting NeoVim

### ISSUE THREAD

**Issue by ashwinkhode** [aurieh/discord.nvim#29] opened 2020-07-14 20:31 UTC
![Annotation 2020-07-15 020025](https://user-images.githubusercontent.com/53361996/87473439-170a1f00-c63f-11ea-9238-e83ade490446.jpg)

OS : Windows 10

**Comment by ObserverOfTime** [comment] 2020-07-15 09:07
Duplicate of #23

**Closed** 2020-07-15 21:51 UTC
Labels: duplicate
