### ISSUE TITLE
Shows previously edited file instead of file being currently edited.

### ISSUE THREAD

**Issue by lelandliu** [aurieh/discord.nvim#9] opened 2018-04-06 03:55 UTC
Using Mac OS with neovim 0.2.2. 

Can reproduce by editing a file, quitting neovim, and editing a different file. Discord says that you're editing the first file.

**Comment by deansheather** [comment] 2018-04-06 10:11
How long do you wait before reopening neovim after you close it? It's probably occurring because Discord hasn't picked up that neovim has closed (because there's still a process) and is still locked on to the first session.

If you do `:DiscordUpdatePresence` in the new neovim window does it update the status?

**Comment by lelandliu** [comment] 2018-04-06 16:31
I suppose I didn't wait too long, maybe a minute at most. :DiscordUpdatePresence doesn't seem to fix it though.

If I just open a file and exit it, discord shows that i'm in the file until I open another file, close it, and switch back to the first file, which makes it show the second file instead of the current (first) file.

Also, not sure if this is related to the issue, but I get some errors when I try to uninstall the plugin using vim-plug. [Error 1](https://i.imgur.com/A8W7TI6.png), [Error 2](https://puu.sh/zXxsk/479ef22864.png). I get the same two errors whenever I try to edit a file afterwards too.

**Comment by aurieh** [comment] 2018-04-07 09:11
Can't reproduce using Discord Canary 0.0.45 on Linux with Neovim 0.2.2.

Also, the only way to cleanly remove a remote plugin is to run `:UpdateRemotePlugins`.

**Comment by lelandliu** [comment] 2018-04-07 17:31
Ah, it seems to be working fine on Linux with discord stable for me too. Perhaps it's just an issue with Mac OS. Thank you for your help though.

**Comment by aurieh** [comment] 2020-01-15 00:44
Closing due to inactivity.

**Closed by aurieh** 2020-01-15 00:44 UTC
Labels: bug, cantrepro
